
####################################################
# SECURITY (Atualizado para Quarkus 3.x)
####################################################

# Ativa o mecanismo de autentica\u00e7\u00e3o (HTTP Basic ou Form )
quarkus.http.auth.basic=true
quarkus.http.auth.form.enabled=true

# 2. Define as rotas das p\u00e1ginas HTML de Login e Erro
quarkus.http.auth.form.login-page=/login.html

# CORRE\u00c7\u00c3O: Nova propriedade do Quarkus 3.x para ativar o fornecedor por ficheiro
quarkus.security.users.file.enabled=true

# Caminho dos ficheiros (dentro de src/main/resources)
quarkus.security.users.file.users=users.properties
quarkus.security.users.file.roles=roles.properties

# Opcional: Garante que as senhas est\u00e3o em texto limpo no users.properties para testes
quarkus.security.users.file.plain-text=true

####################################################
# POL\u00cdTICAS DE ACESSO (Bloqueio Total com Exce\u00e7\u00f5es)
####################################################

# 1. Permite acesso an\u00f4nimo para a p\u00e1gina de login
quarkus.http.auth.permission.public-login.paths=/login.html
quarkus.http.auth.permission.public-login.policy=permit

# 2. Permite acesso an\u00f4nimo para a p\u00e1gina de erro
quarkus.http.auth.permission.public-error.paths=/error.html
quarkus.http.auth.permission.public-error.policy=permit


# 2. Permite acesso p\u00fablico aos recursos est\u00e1ticos globais (CSS, JS, Imagens, Fontes)
#quarkus.http.auth.permission.public-assets.paths=*.css,*.js,*.ico,*.png,*.jpg,*.woff,*.woff2
#quarkus.http.auth.permission.public-assets.policy=permit


# Se o seu servlet do webforJ usar um prefixo espec\u00edfico (ex: /app/*), ajuste aqui.
# Caso use a raiz, o Quarkus gerencia as conex\u00f5es WebSocket por estes caminhos do protocolo.
# webapp/_lib/webapp/webapp.min.js
# /webapprm
# /buires/8749D80ADAF0393D3612E771088DAF7B.gif
# 
quarkus.http.auth.permission.webforj-internal.paths=/webapp/*, /webforj/*, /.well-known/*
quarkus.http.auth.permission.webforj-internal.policy=permit

# 3. Bloqueia TODO o resto da aplica\u00e7\u00e3o (Exige autentica\u00e7\u00e3o)
quarkus.http.auth.permission.lockdown.paths=/, /tasks/*,/api/*
quarkus.http.auth.permission.lockdown.policy=authenticated




